In [1]:
import torch
import torch.nn as nn
from torchsummary import summary

# Batch Normalization

In [2]:
model = nn.Sequential(
    nn.Conv2d(in_channels=1, out_channels=3, kernel_size=3, padding='same', stride=1),
    nn.BatchNorm2d(num_features=3),
    nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, stride=1),
    nn.BatchNorm2d(num_features=16),
    nn.MaxPool2d(kernel_size=2, stride = 2),
    nn.Flatten(),
    nn.BatchNorm1d(num_features=16*13*13),
    nn.Linear(in_features=16*13*13, out_features=256),
    nn.BatchNorm1d(num_features=256)
)

In [3]:
summary(model, input_size=(1,28,28), batch_size=2, device='cpu')

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1             [2, 3, 28, 28]              30
       BatchNorm2d-2             [2, 3, 28, 28]               6
            Conv2d-3            [2, 16, 26, 26]             448
       BatchNorm2d-4            [2, 16, 26, 26]              32
         MaxPool2d-5            [2, 16, 13, 13]               0
           Flatten-6                  [2, 2704]               0
       BatchNorm1d-7                  [2, 2704]           5,408
            Linear-8                   [2, 256]         692,480
       BatchNorm1d-9                   [2, 256]             512
Total params: 698,916
Trainable params: 698,916
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.01
Forward/backward pass size (MB): 0.53
Params size (MB): 2.67
Estimated Total Size (MB): 3.21
-------------------------------------------

# Drop out

In [15]:
model = nn.Sequential(
    nn.Linear(in_features=4, out_features=3),
    nn.Dropout(p=0.7),
    nn.Linear(in_features=3, out_features=2)
)

In [16]:
X = torch.rand(3,4)
X.shape

torch.Size([3, 4])

In [17]:
model[0].weight

Parameter containing:
tensor([[-0.0640,  0.1482,  0.1618, -0.1202],
        [-0.2618,  0.0177, -0.0579,  0.2347],
        [-0.2484, -0.1189,  0.2617, -0.0429]], requires_grad=True)

In [18]:
criterion = nn.CrossEntropyLoss()

In [19]:
optimizer = torch.optim.Adam(model.parameters())

In [20]:
logits = model(X)
logits

tensor([[ 0.2023, -0.3173],
        [-0.0094, -0.3881],
        [-0.5081,  0.3455]], grad_fn=<AddmmBackward0>)

In [21]:
y = torch.tensor([1,0,1],dtype = torch.long)

In [22]:
loss = criterion(logits,y)

In [23]:
loss.backward()

In [24]:
optimizer.step()

In [25]:
model[0].weight

Parameter containing:
tensor([[-0.0640,  0.1482,  0.1618, -0.1202],
        [-0.2628,  0.0167, -0.0589,  0.2337],
        [-0.2474, -0.1179,  0.2627, -0.0419]], requires_grad=True)